### ISSUE TITLE
isbn号已经有了

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/TDbook#7]
https://www.routledge.com/Data-Integration-Manipulation-and-Visualization-of-Phylogenetic-Trees/Yu/p/book/9781032233574

@SanL20 参考一下类似的包，把isbn等信息给加进去包里。

@xiangpin 把tidytree包里的引用信息也更一下，加入这个。

**Comment by SanL20** [comment]
好的老师，我这就去加上。
